# -*- coding: utf-8 -*-
"""Exact strike shift.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eTGXBUWTr4T3il1cVbMQYK1TOvPEZ6Mq
"""

import os
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D            # noqa: F401  (enables 3-D)
from scipy.stats import norm

# --------------------------------------------------------------------------
# 0.  OUTPUT FOLDER AND GLOBAL PLOT STYLE
# --------------------------------------------------------------------------
OUTDIR = "figures"
os.makedirs(OUTDIR, exist_ok=True)

plt.rcParams.update({
    "font.family":      "serif",
    "font.size":        10,
    "axes.titlesize":   11,
    "axes.labelsize":   10,
    "xtick.labelsize":  9,
    "ytick.labelsize":  9,
    "legend.fontsize":  9,
    "figure.dpi":       110,
    "savefig.dpi":      200,
    "savefig.bbox":     "tight",
    "axes.grid":        True,
    "grid.alpha":       0.30,
    "grid.linewidth":   0.5,
    "axes.axisbelow":   True,
})

# Consistent monochrome styling for the three fee structures, so the figures
# remain legible in greyscale print.
FEE_STYLE = {
    "Percentage": dict(color="black",   ls="-",  lw=1.8),
    "Fixed":      dict(color="0.30",    ls="--", lw=1.8),
    "Hybrid":     dict(color="0.30",    ls=":",  lw=2.2),
}

# --------------------------------------------------------------------------
# 1.  SHARED MODEL PARAMETERS  (Table 2 of the paper)
# --------------------------------------------------------------------------
C0    = 50.0      # base cost estimate, $M
T     = 2.5       # project duration, years
SIGMA = 0.18      # composite cost volatility (constant-parameter baseline)
MU    = 0.04      # expected real-world cost escalation rate
R     = 0.08      # risk-free rate (US construction-lending benchmark)

# fee structures: (percentage fee f, fixed fee F in $M)
FEES = {
    "Percentage": dict(f=0.08, F=0.0),
    "Fixed":      dict(f=0.00, F=4.0),
    "Hybrid":     dict(f=0.06, F=2.0),
}

Z_CONTRACTOR = norm.ppf(1 - 0.10)     # z at alpha = 10%  -> 1.2816
Z_BANK       = norm.ppf(1 - 0.05)     # z at alpha =  5%  -> 1.6449

# time-varying schedule constants (Section 9.1)
SIG0, SIG_MIN, LAMBDA, GAMMA = 0.22, 0.12, 1.8, 1.2
R0, R1, R2                   = 0.10, 0.04, 0.01

# --------------------------------------------------------------------------
# 2.  CORE MODEL FUNCTIONS
# --------------------------------------------------------------------------
def adjusted_strike(K, f, F):
    """Equation (3): K' = (K - F) / (1 + f)."""
    return (K - F) / (1.0 + f)


def bs_call(C0, Kp, sigma, r, tau):
    """Bare Black-Scholes call value on the cost process (Eq. 9 inner term)."""
    d1 = (np.log(C0 / Kp) + (r + 0.5 * sigma**2) * tau) / (sigma * np.sqrt(tau))
    d2 = d1 - sigma * np.sqrt(tau)
    return C0 * norm.cdf(d1) - Kp * np.exp(-r * tau) * norm.cdf(d2)


def gmp_loss_premium(C0, Kp, sigma, r, tau, f):
    """Equation (9): GMP loss premium  V = (1 + f) * call(C0, K')."""
    return (1.0 + f) * bs_call(C0, Kp, sigma, r, tau)


def k_star(C0, sigma, r, T, z, f, F):
    """Equation (11): minimum acceptable GMP cap K*."""
    return (1.0 + f) * C0 * np.exp((r - 0.5 * sigma**2) * T
                                   + z * sigma * np.sqrt(T)) + F


def sigma_schedule(t, T):
    """Equation (13): stretched-exponential decline of cost volatility."""
    return SIG_MIN + (SIG0 - SIG_MIN) * np.exp(-LAMBDA * (t / T)**GAMMA)


def r_schedule(t, T):
    """Equation (14): phase-modulated risk-free rate."""
    return R0 - R1 * np.sin(np.pi * t / T) + R2 * (t / T)


def solve_pde(Kp, sigma_const, r_const, T,
              N=80, C_max=200.0, dtau=0.002,
              time_varying=False, store_every=20):
    """
    Explicit-Euler finite-difference solver for the Black-Scholes PDE
    (Eq. 12), posed in transformed time tau = T - t.

    Returns
    -------
    C     : cost grid, shape (N+1,)
    taus  : stored transformed-time values
    snaps : option-value snapshots, shape (len(taus), N+1)
    """
    dC = C_max / N
    C  = np.linspace(0.0, C_max, N + 1)
    V  = np.maximum(C - Kp, 0.0)                 # initial condition (tau = 0)

    nsteps = int(round(T / dtau))
    snaps, taus = [V.copy()], [0.0]

    for s in range(nsteps):
        tau = (s + 1) * dtau
        if time_varying:
            t_cal = T - tau                      # calendar time
            sig   = sigma_schedule(t_cal, T)
            rr    = r_schedule(t_cal, T)
        else:
            sig, rr = sigma_const, r_const

        # centred finite differences on the interior nodes
        d2V = (V[2:] - 2.0 * V[1:-1] + V[:-2]) / dC**2
        d1V = (V[2:] - V[:-2]) / (2.0 * dC)
        dVdtau = (0.5 * sig**2 * C[1:-1]**2 * d2V
                  + rr * C[1:-1] * d1V
                  - rr * V[1:-1])

        Vn = V.copy()
        Vn[1:-1] = V[1:-1] + dtau * dVdtau
        Vn[0]    = 0.0                                   # lower Dirichlet BC
        Vn[-1]   = C_max - Kp * np.exp(-rr * tau)        # upper Dirichlet BC
        V = Vn

        if (s + 1) % store_every == 0 or s == nsteps - 1:
            snaps.append(V.copy())
            taus.append(tau)

    return C, np.array(taus), np.array(snaps)


def header(fig, text):
    """Place the figure TITLE only (no 'Fig. N.' label) above the panels."""
    fig.suptitle(text, fontsize=11, fontweight="bold", y=1.02)


def save(fig, name):
    path = os.path.join(OUTDIR, name)
    fig.savefig(path)
    plt.close(fig)
    print(f"  saved  {path}")

# ==========================================================================
# FIGURE 1  ->  fig1_payoff_three_fees.png
# ==========================================================================
def fig1_payoff_three_fees():
    """Contractor payoff under percentage, fixed and hybrid fee structures."""
    K = 68.0                                   # nominal cap for this figure
    C = np.linspace(45.0, 92.0, 400)

    panels = [
        ("Percentage fee",  0.08, 0.0,  r"$\varphi(C)=fC,\ f=0.08$"),
        ("Fixed fee",       0.00, 4.0,  r"$\varphi(C)=F,\ F=\$4$M"),
        ("Hybrid fee",      0.06, 2.0,  r"$\varphi(C)=fC+F$"),
    ]
    # K' formula strings shown inside each panel title (no overlap with legend)
    kp_formula = [
        r"$K'=K/(1{+}f)=\$%.2f$M",
        r"$K'=K{-}F=\$%.2f$M",
        r"$K'=(K{-}F)/(1{+}f)=\$%.2f$M",
    ]

    fig, axes = plt.subplots(1, 3, figsize=(11.5, 4.0), sharey=True)

    for ax, (label, f, F, phi), kpf in zip(axes, panels, kp_formula):
        Kp     = adjusted_strike(K, f, F)
        payoff = -(1.0 + f) * np.maximum(C - Kp, 0.0)

        # contractor payoff curve
        ax.plot(C, payoff, color="black", lw=2.0, label="Contractor payoff")
        # shaded loss zone (region where payoff < 0)
        ax.fill_between(C, payoff, 0.0, where=(payoff < 0),
                        color="0.80", label="Loss zone")
        # adjusted-strike marker
        ax.axvline(Kp, color="0.35", ls="--", lw=1.3)
        ax.axhline(0.0, color="black", lw=0.8)

        # --- FIX: K' equation goes in the TITLE, legend goes in the empty
        #     lower-left corner, so the two no longer overlap. ---
        ax.set_title(f"{label}\n{phi}\n{kpf % Kp}", fontsize=9.5)
        ax.legend(loc="lower left", framealpha=0.95, fontsize=8.5)

        ax.set_xlabel(r"Actual cost $C(T)$  (\$M)")
        ax.set_xlim(C.min(), C.max())
        ax.set_ylim(-32, 4)
        ax.grid(alpha=0.30)

    axes[0].set_ylabel(r"Contractor payoff  (\$M)")

    header(fig, r"Contractor payoff $-(1{+}f)\max[C(T)-K',0]$ "
                r"under three fee structures ($K=\$68$M)")
    fig.tight_layout()
    save(fig, "fig1_payoff_three_fees.png")


# ==========================================================================
# FIGURE 2  ->  fig4_strike_shift.png
# ==========================================================================
def fig2_strike_shift():
    """Adjusted strike K' as a function of the nominal GMP cap K."""
    K = np.linspace(55.0, 90.0, 200)

    fig, ax = plt.subplots(figsize=(6.0, 4.6))

    for name, pars in FEES.items():
        Kp = adjusted_strike(K, pars["f"], pars["F"])
        ax.plot(K, Kp, label=f"{name}: f={pars['f']:.2f}, F=\\${pars['F']:.0f}M",
                **FEE_STYLE[name])

    # reference line K' = K (no fee)
    ax.plot(K, K, color="0.55", ls="-.", lw=1.2, label=r"$K'=K$ (reference)")

    ax.set_xlabel(r"Nominal GMP cap $K$  (\$M)")
    ax.set_ylabel(r"Adjusted strike $K'$  (\$M)")
    ax.set_xlim(K.min(), K.max())
    ax.legend(loc="upper left")
    ax.grid(alpha=0.30)

    header(fig, r"Adjusted strike $K'=(K-F)/(1+f)$ vs nominal GMP cap $K$")
    fig.tight_layout()
    save(fig, "fig4_strike_shift.png")


# ==========================================================================
# FIGURE 3  ->  fig2_gbm_paths.png
# ==========================================================================
def fig3_gbm_paths():
    """Simulated geometric-Brownian-motion cost paths."""
    rng    = np.random.default_rng(42)
    n      = 200
    nsteps = 250
    t      = np.linspace(0.0, T, nsteps + 1)
    dt     = T / nsteps

    K  = 65.0
    Kp = adjusted_strike(K, FEES["Percentage"]["f"], FEES["Percentage"]["F"])

    # simulate paths
    paths = np.empty((n, nsteps + 1))
    paths[:, 0] = C0
    for i in range(n):
        Z = rng.standard_normal(nsteps)
        incr = (MU - 0.5 * SIGMA**2) * dt + SIGMA * np.sqrt(dt) * Z
        paths[i, 1:] = C0 * np.exp(np.cumsum(incr))

    breach = paths[:, -1] > Kp

    fig, ax = plt.subplots(figsize=(6.2, 4.8))

    for i in range(n):
        if breach[i]:
            ax.plot(t, paths[i], color="black", lw=0.5, alpha=0.55)
        else:
            ax.plot(t, paths[i], color="0.72", lw=0.5, alpha=0.7)

    ax.axhline(Kp, color="black", ls="--", lw=1.8,
               label=fr"$K'=\${Kp:.2f}$M (adjusted strike)")
    ax.axhline(C0, color="0.30", ls=":", lw=1.5, label=r"$C_0=\$50$M")

    ax.set_xlabel("Time  (years)")
    ax.set_ylabel(r"Project cost $C(t)$  (\$M)")
    ax.set_xlim(0, T)
    ax.legend(loc="upper left")
    ax.grid(alpha=0.30)

    pct = 100.0 * breach.mean()
    header(fig, r"Simulated GBM cost paths $C(t)$ "
                fr"($n=200$;  {pct:.0f}% breach $K'$ under % fee)")
    fig.tight_layout()
    save(fig, "fig2_gbm_paths.png")


# ==========================================================================
# FIGURE 4  ->  fig5_v_vs_sigma.png
# ==========================================================================
def fig4_v_vs_sigma():
    """GMP loss premium V as a function of cost volatility sigma."""
    sigma = np.linspace(0.05, 0.40, 200)
    K     = 65.0

    fig, ax = plt.subplots(figsize=(6.0, 4.6))

    for name, pars in FEES.items():
        f, F = pars["f"], pars["F"]
        Kp   = adjusted_strike(K, f, F)
        V    = gmp_loss_premium(C0, Kp, sigma, R, T, f)
        ax.plot(sigma, V, label=f"{name}: f={f:.2f}, F=\\${F:.0f}M",
                **FEE_STYLE[name])

    ax.set_xlabel(r"Cost volatility $\sigma$")
    ax.set_ylabel(r"GMP loss premium $V$  (\$M)")
    ax.set_xlim(sigma.min(), sigma.max())
    ax.legend(loc="upper left")
    ax.grid(alpha=0.30)

    header(fig, r"GMP loss premium $V$ vs cost volatility $\sigma$ "
                r"for three fee structures")
    fig.tight_layout()
    save(fig, "fig5_v_vs_sigma.png")


# ==========================================================================
# FIGURE 5  ->  fig3_kstar_vs_sigma.png
# ==========================================================================
def fig5_kstar_vs_sigma():
    """Minimum acceptable GMP cap K* as a function of volatility."""
    sigma = np.linspace(0.05, 0.40, 200)

    fig, ax = plt.subplots(figsize=(6.0, 4.6))

    for name, pars in FEES.items():
        f, F = pars["f"], pars["F"]
        Ks   = k_star(C0, sigma, R, T, Z_CONTRACTOR, f, F)
        ax.plot(sigma, Ks, label=f"{name}: f={f:.2f}, F=\\${F:.0f}M",
                **FEE_STYLE[name])

    # conventional +15% contingency buffer (percentage-fee base)
    conv = 1.15 * (1.0 + FEES["Percentage"]["f"]) * C0
    ax.axhline(conv, color="0.55", ls="-.", lw=1.3,
               label=r"Conventional +15% buffer")

    ax.set_xlabel(r"Cost volatility $\sigma$")
    ax.set_ylabel(r"Minimum acceptable GMP $K^{*}$  (\$M)")
    ax.set_xlim(sigma.min(), sigma.max())
    ax.legend(loc="upper left")
    ax.grid(alpha=0.30)

    header(fig, r"Minimum acceptable GMP $K^{*}$ vs cost volatility "
                r"$\sigma$  ($\alpha=10\%$)")
    fig.tight_layout()
    save(fig, "fig3_kstar_vs_sigma.png")


# ==========================================================================
# FIGURE 6  ->  figSD1_schedules.png
# ==========================================================================
def fig6_schedules():
    """Time-varying parameter schedules used by the SD-PDE solver."""
    t = np.linspace(0.0, T, 200)

    fig, (axL, axR) = plt.subplots(1, 2, figsize=(10.5, 4.2))

    # (a) risk-free rate r(t)
    axL.plot(t, r_schedule(t, T), color="black", lw=2.0,
             label=r"$r(t)$ time-varying")
    axL.axhline(R, color="0.45", ls="--", lw=1.4,
                label=fr"$r={R:.2f}$ (constant baseline)")
    axL.fill_between(t, r_schedule(t, T), R, color="0.85")
    axL.set_title("(a)  Time-varying discount rate $r(t)$", fontsize=10)
    axL.set_xlabel("Project time  (years)")
    axL.set_ylabel(r"Discount rate $r(t)$")
    axL.set_xlim(0, T)
    axL.legend(loc="best")
    axL.grid(alpha=0.30)

    # (b) cost volatility sigma(t)
    axR.plot(t, sigma_schedule(t, T), color="black", lw=2.0,
             label=r"$\sigma(t)$ time-varying")
    axR.axhline(SIGMA, color="0.45", ls="--", lw=1.4,
                label=fr"$\sigma={SIGMA:.2f}$ (constant baseline)")
    axR.fill_between(t, sigma_schedule(t, T), SIGMA, color="0.85")
    axR.set_title("(b)  Time-varying cost volatility $\\sigma(t)$", fontsize=10)
    axR.set_xlabel("Project time  (years)")
    axR.set_ylabel(r"Cost volatility $\sigma(t)$")
    axR.set_xlim(0, T)
    axR.legend(loc="best")
    axR.grid(alpha=0.30)

    header(fig, "Time-varying parameter schedules used in the "
                "SD-PDE simulation")
    fig.tight_layout()
    save(fig, "figSD1_schedules.png")


# ==========================================================================
# FIGURE 8  ->  anylogic_outputs.png
# ==========================================================================
def fig8_anylogic_outputs():
    """SD-PDE solver outputs: V(C0, tau) over time, and V(C, T) profile."""
    K  = 65.0
    f  = FEES["Percentage"]["f"]
    Kp = adjusted_strike(K, f, FEES["Percentage"]["F"])

    C, taus, snaps = solve_pde(Kp, SIGMA, R, T, N=80, C_max=200.0,
                               dtau=0.002, store_every=10)

    idx_C0  = int(round(C0 / (C[1] - C[0])))      # grid index at C = C0
    V_at_C0 = snaps[:, idx_C0]
    V_final = snaps[-1]

    fig, (axL, axR) = plt.subplots(1, 2, figsize=(10.0, 3.9))

    # (a) option value at the base cost estimate, V(C0, tau)
    axL.plot(taus, V_at_C0, color="black", lw=2.0)
    axL.scatter([taus[-1]], [V_at_C0[-1]], color="black", zorder=5)
    axL.annotate(fr"$V(C_0,T)\approx\${V_at_C0[-1]:.2f}$M",
                 xy=(taus[-1], V_at_C0[-1]),
                 xytext=(taus[-1] * 0.45, V_at_C0[-1] * 0.78),
                 fontsize=9,
                 arrowprops=dict(arrowstyle="->", color="0.4"))
    axL.set_title(r"(a)  Option value at base estimate $V(C_0,\tau)$",
                  fontsize=10)
    axL.set_xlabel(r"Transformed time $\tau=T-t$  (years)")
    axL.set_ylabel(r"Option value $V(C_0,\tau)$  (\$M)")
    axL.set_xlim(0, T)
    axL.grid(alpha=0.30)

    # (b) value profile across the cost grid at tau = T
    axR.plot(C, V_final, color="black", lw=2.0, label=r"$V(C,\tau=T)$")
    axR.plot(C, np.maximum(C - Kp, 0.0), color="0.55", ls="--", lw=1.4,
             label=r"terminal payoff $\max(C-K',0)$")
    axR.axvline(Kp, color="0.35", ls=":", lw=1.3)
    axR.set_title(r"(b)  Value profile $V(C,\tau=T)$ across cost grid",
                  fontsize=10)
    axR.set_xlabel(r"Project cost $C$  (\$M)")
    axR.set_ylabel(r"Option value $V$  (\$M)")
    axR.set_xlim(0, 200)
    axR.legend(loc="upper left")
    axR.grid(alpha=0.30)

    header(fig, "SD-PDE simulation outputs")
    fig.tight_layout()
    save(fig, "anylogic_outputs.png")


# ==========================================================================
# FIGURE 9  ->  value_surface.png
# ==========================================================================
def fig9_value_surface():
    """3-D option-value surface V(C, tau) produced by the SD-PDE solver."""
    K  = 65.0
    Kp = adjusted_strike(K, FEES["Percentage"]["f"], FEES["Percentage"]["F"])

    C, taus, snaps = solve_pde(Kp, SIGMA, R, T, N=80, C_max=160.0,
                               dtau=0.002, store_every=25)

    Cg, Tg = np.meshgrid(C, taus)

    fig = plt.figure(figsize=(7.4, 5.6))
    ax  = fig.add_subplot(111, projection="3d")

    surf = ax.plot_surface(Cg, Tg, snaps, cmap="viridis",
                           linewidth=0, antialiased=True,
                           rstride=1, cstride=2)

    ax.set_xlabel(r"Project cost $C$  (\$M)", labelpad=8)
    ax.set_ylabel(r"Transformed time $\tau$  (years)", labelpad=8)
    ax.set_zlabel(r"Option value $V$  (\$M)", labelpad=6)
    ax.view_init(elev=26, azim=-128)
    fig.colorbar(surf, shrink=0.6, aspect=14, pad=0.10,
                 label=r"$V(C,\tau)$  (\$M)")

    header(fig, r"GMP option-value surface $V(C,\tau)$ "
                r"from the SD-PDE solver")
    fig.tight_layout()
    save(fig, "value_surface.png")


# ==========================================================================
# FIGURE 10  ->  fig6_mc_dist.png
# ==========================================================================
def fig10_mc_distribution():
    """Monte-Carlo distribution of terminal cost C(T) versus K'."""
    rng = np.random.default_rng(7)
    n   = 4000
    K   = 65.0

    # one shared set of terminal-cost draws (the strike-shift idea: vary K' only)
    Z  = rng.standard_normal(n)
    CT = C0 * np.exp((MU - 0.5 * SIGMA**2) * T + SIGMA * np.sqrt(T) * Z)

    fig, axes = plt.subplots(1, 3, figsize=(11.5, 4.0), sharey=True)

    for ax, (name, pars) in zip(axes, FEES.items()):
        f, F = pars["f"], pars["F"]
        Kp   = adjusted_strike(K, f, F)

        below = CT[CT <= Kp]
        above = CT[CT > Kp]
        bins  = np.linspace(CT.min(), CT.max(), 45)

        ax.hist(below, bins=bins, color="0.78", edgecolor="white",
                linewidth=0.3, label=r"$C(T)\leq K'$")
        ax.hist(above, bins=bins, color="0.25", edgecolor="white",
                linewidth=0.3, label=r"$C(T)>K'$")
        ax.axvline(Kp, color="black", ls="--", lw=1.8,
                   label=fr"$K'=\${Kp:.2f}$M")

        pct = 100.0 * (CT > Kp).mean()
        ax.set_title(f"{name}:  f={f:.2f}, F=\\${F:.0f}M\n"
                     fr"$K'=\${Kp:.1f}$M;  {pct:.1f}% exceed $K'$",
                     fontsize=9.5)
        ax.set_xlabel(r"Terminal cost $C(T)$  (\$M)")
        ax.legend(loc="upper right", fontsize=8.5)
        ax.grid(alpha=0.30)

    axes[0].set_ylabel("Frequency")

    header(fig, r"Monte Carlo distribution of $C(T)$ vs $K'$ "
                r"under three fee structures")
    fig.tight_layout()
    save(fig, "fig6_mc_dist.png")


# ==========================================================================
# FIGURE 11  ->  figSD3_validation.png
# ==========================================================================
def fig11_validation():
    """Three-method validation: closed form, Monte Carlo, SD-PDE."""
    rng = np.random.default_rng(11)
    K   = 65.0
    f   = FEES["Percentage"]["f"]
    F   = FEES["Percentage"]["F"]
    Kp  = adjusted_strike(K, f, F)

    def mc_premium(sigma, r, T, n=20000):
        """Monte-Carlo estimate of the discounted GMP loss premium."""
        Z   = rng.standard_normal(n)
        CT  = C0 * np.exp((r - 0.5 * sigma**2) * T + sigma * np.sqrt(T) * Z)
        pay = (1.0 + f) * np.maximum(CT - Kp, 0.0)
        return np.exp(-r * T) * pay.mean()

    def pde_premium(sigma, r, T):
        """SD-PDE estimate of the GMP loss premium at (C0, T)."""
        C, _, snaps = solve_pde(Kp, sigma, r, T, N=80, C_max=200.0,
                                dtau=0.002, store_every=10**6)
        idx = int(round(C0 / (C[1] - C[0])))
        return (1.0 + f) * snaps[-1, idx]

    fig, axes = plt.subplots(1, 3, figsize=(12.0, 3.9))

    # ---- (a)  V vs sigma ----
    sig_line = np.linspace(0.08, 0.32, 120)
    V_line   = gmp_loss_premium(C0, Kp, sig_line, R, T, f)
    sig_pts  = np.array([0.10, 0.16, 0.22, 0.28])
    V_mc     = np.array([mc_premium(s, R, T)  for s in sig_pts])
    V_pde    = np.array([pde_premium(s, R, T) for s in sig_pts])

    axes[0].plot(sig_line, V_line, color="black", lw=1.8,
                 label="Closed-form")
    axes[0].scatter(sig_pts, V_mc, marker="o", s=42, facecolor="white",
                    edgecolor="black", zorder=5, label="Monte Carlo")
    axes[0].scatter(sig_pts, V_pde, marker="s", s=38, color="0.35",
                    zorder=5, label="SD-PDE")
    axes[0].set_title(r"(a)  $V$ vs volatility $\sigma$", fontsize=10)
    axes[0].set_xlabel(r"Cost volatility $\sigma$")
    axes[0].set_ylabel(r"GMP loss premium $V$  (\$M)")
    axes[0].legend(loc="upper left")
    axes[0].grid(alpha=0.30)

    # ---- (b)  V vs duration T ----
    T_line = np.linspace(1.0, 3.5, 120)
    Vt_line = gmp_loss_premium(C0, Kp, SIGMA, R, T_line, f)
    T_pts   = np.array([1.5, 2.0, 2.5, 3.0])
    Vt_mc   = np.array([mc_premium(SIGMA, R, t)  for t in T_pts])
    Vt_pde  = np.array([pde_premium(SIGMA, R, t) for t in T_pts])

    axes[1].plot(T_line, Vt_line, color="black", lw=1.8, label="Closed-form")
    axes[1].scatter(T_pts, Vt_mc, marker="o", s=42, facecolor="white",
                    edgecolor="black", zorder=5, label="Monte Carlo")
    axes[1].scatter(T_pts, Vt_pde, marker="s", s=38, color="0.35",
                    zorder=5, label="SD-PDE")
    axes[1].set_title(r"(b)  $V$ vs project duration $T$", fontsize=10)
    axes[1].set_xlabel(r"Project duration $T$  (years)")
    axes[1].set_ylabel(r"GMP loss premium $V$  (\$M)")
    axes[1].legend(loc="upper left")
    axes[1].grid(alpha=0.30)

    # ---- (c)  K* vs exceedance tolerance alpha ----
    alpha = np.linspace(0.01, 0.20, 120)
    z_arr = norm.ppf(1.0 - alpha)
    Ks    = k_star(C0, SIGMA, R, T, z_arr, f, F)
    axes[2].plot(alpha * 100, Ks, color="black", lw=1.8)

    for a, z, lab, mk in [(0.10, Z_CONTRACTOR, "Contractor", "o"),
                          (0.05, Z_BANK,       "Bank",       "s")]:
        Kpt = k_star(C0, SIGMA, R, T, z, f, F)
        axes[2].scatter([a * 100], [Kpt], marker=mk, s=55, zorder=5,
                        color="black",
                        label=fr"{lab} ($\alpha={a*100:.0f}\%$): $K^*=\${Kpt:.1f}$M")

    axes[2].set_title(r"(c)  $K^{*}$ vs exceedance tolerance $\alpha$",
                      fontsize=10)
    axes[2].set_xlabel(r"Exceedance tolerance $\alpha$  (%)")
    axes[2].set_ylabel(r"Minimum acceptable GMP $K^{*}$  (\$M)")
    axes[2].legend(loc="upper right", fontsize=8)
    axes[2].grid(alpha=0.30)

    header(fig, "Three-method validation: closed-form, Monte Carlo, "
                "and SD-PDE")
    fig.tight_layout()
    save(fig, "figSD3_validation.png")


# ==========================================================================
# FIGURE 12  ->  fig7_bayesian.png
#   Corrections vs the previous version:
#     * 24 reporting periods (x-axis 0-25), matching the paper -- was 30.
#     * Observation noise removed from the synthetic Earned-Value series, so
#       the posterior mean and the breach probability P_k both come out as
#       the smooth, monotone curves shown in the paper -- the previous
#       version injected random noise that made panel (b) rise to ~70%
#       mid-project before falling, which is physically wrong.
# ==========================================================================
def fig12_bayesian():
    """Bayesian sequential updating of the cost posterior and breach prob."""
    n_period = 24                                  # monthly reporting periods
    months   = np.arange(0, n_period + 1)
    K        = 65.0
    f        = FEES["Percentage"]["f"]
    Kp       = adjusted_strike(K, f, FEES["Percentage"]["F"])

    # ground-truth cost-at-completion the project is really heading toward
    C_true = 57.0

    # Synthetic Earned-Value cost-at-completion estimates A_k = ACWP_k / CPI_k.
    # The estimate drifts smoothly from the base estimate C0 toward the true
    # final cost as the work proceeds.  No random noise is added: the Bayesian
    # filter is being illustrated, so the observation stream is the expected
    # (mean) EV signal and the posterior therefore evolves smoothly.
    cac = C_true - (C_true - C0) * np.exp(-months / 7.0)

    # prior on log-cost
    mu, var = np.log(C0), 0.07
    mu_hist          = [mu]
    lo_hist, hi_hist = [np.exp(mu - 1.96 * np.sqrt(var))], \
                       [np.exp(mu + 1.96 * np.sqrt(var))]

    # breach probability from the prior (period 0)
    P_hist = [1.0 - norm.cdf((np.log(Kp) - mu - (R - 0.5 * var) * T) /
                             (np.sqrt(var) * np.sqrt(T)))]

    for k in range(1, n_period + 1):
        # observation precision improves as the project matures: the EV
        # signal is noisier early (var_obs = 0.10) and sharper late (0.05)
        var_obs = 0.10 if k < n_period * 0.5 else 0.05
        alpha_k = np.log(cac[k])                  # expected log-cost signal

        # conjugate Gaussian update (Eqs. 19-20)
        var_new = 1.0 / (1.0 / var + 1.0 / var_obs)
        mu      = var_new * (mu / var + alpha_k / var_obs)
        var     = var_new

        mu_hist.append(mu)
        lo_hist.append(np.exp(mu - 1.96 * np.sqrt(var)))
        hi_hist.append(np.exp(mu + 1.96 * np.sqrt(var)))

        # breach probability against K' (Eq. 21)
        tau_k = max(T * (1.0 - k / n_period), 1e-6)
        z     = (np.log(Kp) - mu - (R - 0.5 * var) * tau_k) / \
                (np.sqrt(var) * np.sqrt(tau_k))
        P_hist.append(1.0 - norm.cdf(z))

    C_hat  = np.exp(np.array(mu_hist))
    P_hist = np.array(P_hist)

    fig, (axL, axR) = plt.subplots(1, 2, figsize=(11.0, 4.2))

    # (a) posterior cost evolution with 95% credible interval
    axL.fill_between(months, lo_hist, hi_hist, color="0.85",
                     label="95% credible interval")
    axL.plot(months, C_hat, color="black", lw=2.0,
             label=r"posterior mean $\hat{C}(k)$")
    axL.axhline(C_true, color="black", ls="--", lw=1.6,
                label=fr"true $C(T)=\${C_true:.0f}$M")
    axL.axhline(Kp, color="black", ls=":", lw=1.6,
                label=fr"$K'=\${Kp:.1f}$M")
    axL.set_title("(a)  Posterior cost evolution", fontsize=10)
    axL.set_xlabel("Reporting period $k$")
    axL.set_ylabel(r"Cost estimate  (\$M)")
    axL.set_xlim(0, n_period + 1)
    axL.legend(loc="upper right", fontsize=8.5)
    axL.grid(alpha=0.30)

    # (b) GMP breach probability -- smooth monotone decline
    axR.plot(months, 100.0 * P_hist, color="black", lw=2.0,
             label=r"$P(C(T)>K')$")
    axR.axhline(10.0, color="black", ls="--", lw=1.5,
                label="10% alert threshold")
    axR.set_title(r"(b)  GMP breach probability $P(C(T)>K')$", fontsize=10)
    axR.set_xlabel("Reporting period $k$")
    axR.set_ylabel(r"$P(C(T)>K')$  (%)")
    axR.set_xlim(0, n_period + 1)
    axR.set_ylim(0, 80)
    axR.legend(loc="upper right", fontsize=8.5)
    axR.grid(alpha=0.30)

    header(fig, "Bayesian sequential updating across 24 monthly "
                "reporting periods")
    fig.tight_layout()
    save(fig, "fig7_bayesian.png")


# ==========================================================================
# FIGURE 13  ->  fig8_sensitivity.png
# ==========================================================================
def fig13_sensitivity():
    """Sensitivity of K* to (sigma, T) and of V to the contingency buffer."""
    fig, (axL, axR) = plt.subplots(1, 2, figsize=(11.0, 4.2))

    # (a) K* vs sigma for four project durations
    sigma = np.linspace(0.08, 0.40, 160)
    f, F  = FEES["Percentage"]["f"], FEES["Percentage"]["F"]
    durations = [1.5, 2.0, 2.5, 3.5]
    dur_styles = [dict(ls=":",  lw=1.6),
                  dict(ls="--", lw=1.6),
                  dict(ls="-",  lw=2.0),
                  dict(ls="-.", lw=1.8)]
    for T_d, st in zip(durations, dur_styles):
        Ks = k_star(C0, sigma, R, T_d, Z_CONTRACTOR, f, F)
        axL.plot(sigma, Ks, color="black", label=fr"$T={T_d}$ yr", **st)
    axL.set_title(r"(a)  $K^{*}$ vs $\sigma$ for four project durations",
                  fontsize=10)
    axL.set_xlabel(r"Cost volatility $\sigma$")
    axL.set_ylabel(r"Minimum acceptable GMP $K^{*}$  (\$M)")
    axL.set_xlim(sigma.min(), sigma.max())
    axL.legend(loc="upper left")
    axL.grid(alpha=0.30)

    # (b) GMP loss premium V vs contingency buffer above C0
    buffer = np.linspace(0.0, 30.0, 160)         # $M above the base estimate
    for name, pars in FEES.items():
        f, F = pars["f"], pars["F"]
        K    = C0 + buffer                       # nominal cap
        Kp   = adjusted_strike(K, f, F)
        V    = gmp_loss_premium(C0, Kp, SIGMA, R, T, f)
        axR.plot(buffer, V, label=f"{name}: f={f:.2f}, F=\\${F:.0f}M",
                 **FEE_STYLE[name])
    axR.set_title(r"(b)  GMP loss premium $V$ vs contingency buffer",
                  fontsize=10)
    axR.set_xlabel(r"Buffer above $C_0$  (\$M)")
    axR.set_ylabel(r"GMP loss premium $V$  (\$M)")
    axR.set_xlim(0, 30)
    axR.legend(loc="upper right")
    axR.grid(alpha=0.30)

    header(fig, "Sensitivity analysis")
    fig.tight_layout()
    save(fig, "fig8_sensitivity.png")


# ==========================================================================
# FIGURE 14  ->  fig9_lifecycle.png
#   Corrections vs the previous version:
#     * Two pre-award K* curves -- % fee and fixed fee -- were one.
#     * Both K* curves run across the whole 0-60% pre-award span; the
#       contract award is at 60% of the lifecycle (was split at 50%).
#     * The post-award posterior is plotted as a dotted Q(t) curve with a
#       shaded credible band over 60-100%.
#     * The negotiated cap K = $65M is drawn as a chain-dotted line.
# ==========================================================================
def fig14_lifecycle():
    """Lifecycle risk evolution: pre-award K* (two fees) and post-award Q(t)."""
    K_nominal = 65.0
    award     = 60.0                               # contract award at 60%

    # ---- pre-award phase (0 -> 60% of lifecycle): design matures, sigma falls
    stage_pre = np.linspace(0.0, award, 90)
    # cost volatility declines from AACE Class-5 (~0.30) toward Class-2 (~0.15)
    sigma_pre = 0.15 + 0.15 * np.exp(-3.0 * (stage_pre / award))

    Kstar_pct = k_star(C0, sigma_pre, R, T, Z_CONTRACTOR,
                       FEES["Percentage"]["f"], FEES["Percentage"]["F"])
    Kstar_fix = k_star(C0, sigma_pre, R, T, Z_CONTRACTOR,
                       FEES["Fixed"]["f"], FEES["Fixed"]["F"])

    # ---- post-award phase (60 -> 100%): Bayesian posterior cost Q(t) converges
    stage_post = np.linspace(award, 100.0, 90)
    frac       = (stage_post - award) / (100.0 - award)
    Q_post     = 57.0 - 4.0 * np.exp(-2.2 * frac)      # converges toward $57M
    band       = 11.0 * np.exp(-1.8 * frac)            # shrinking 95% band

    fig, ax = plt.subplots(figsize=(7.0, 4.8))

    # pre-award: two minimum-acceptable-cap curves
    ax.plot(stage_pre, Kstar_pct, color="black", ls="-", lw=2.0,
            label=r"$K^{*}$ (% fee)")
    ax.plot(stage_pre, Kstar_fix, color="black", ls="--", lw=1.8,
            label=r"$K^{*}$ (fixed fee)")

    # post-award: posterior cost estimate Q(t) with shaded credible band
    ax.fill_between(stage_post, Q_post - band, Q_post + band, color="0.85")
    ax.plot(stage_post, Q_post, color="black", ls=":", lw=2.4,
            label="Posterior Q(t) (post-award)")

    # negotiated cap reference (chain-dotted) and award marker
    ax.axhline(K_nominal, color="black", ls="-.", lw=1.3,
               label=fr"$K=\${K_nominal:.0f}$M")
    ax.axvline(award, color="0.65", ls=":", lw=1.0)
    ax.annotate("Award", xy=(award, K_nominal), xytext=(award - 13.0, 71.0),
                fontsize=9, va="center",
                arrowprops=dict(arrowstyle="->", color="0.5"))

    ax.set_xlabel("Project lifecycle stage  (%)")
    ax.set_ylabel(r"$K^{*}$ or Q(t)  (\$M)")
    ax.set_xlim(-2, 102)
    ax.legend(loc="upper right", fontsize=8.5)
    ax.grid(alpha=0.30)

    header(fig, "Lifecycle risk evolution")
    fig.tight_layout()
    save(fig, "fig9_lifecycle.png")

# ==========================================================================blob:https://colab.research.google.com/72c54a39-2894-42e4-a5ee-b1cb556c4f7f$0
# MAIN
# ==========================================================================
def main():
    print("Generating paper figures into ./%s/ ..." % OUTDIR)
    fig1_payoff_three_fees()      # Fig. 1
    fig2_strike_shift()           # Fig. 2
    fig3_gbm_paths()              # Fig. 3
    fig4_v_vs_sigma()             # Fig. 4
    fig5_kstar_vs_sigma()         # Fig. 5
    fig6_schedules()              # Fig. 6
    fig8_anylogic_outputs()       # Fig. 8
    fig9_value_surface()          # Fig. 9
    fig10_mc_distribution()       # Fig. 10
    fig11_validation()            # Fig. 11
    fig12_bayesian()              # Fig. 12
    fig13_sensitivity()           # Fig. 13
    fig14_lifecycle()             # Fig. 14
    print("Done - 13 figures written.")


if __name__ == "__main__":
    main()